name: flutter_android_serial
description: returns Secure.ANDROID_ID
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutter_android_serial
    pluginClass: FlutterAndroidSerialPlugin
